service: url-shortener

frameworkVersion: "2"

custom:
  codesTable: "urlshortener.codes.${self:provider.stage}"

  rack:
    configPath: src/config.ru

provider:
  name: aws
  runtime: ruby2.7
  lambdaHashingVersion: "20201221"
  stage: dev
  apiGateway:
    shouldStartNameWithService: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [CodesTable, Arn]
  environment:
    CODES_TABLE: ${self:custom.codesTable}

functions:
  api:
    handler: rack_adapter.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-rack

resources:
  Resources:
    CodesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
          - AttributeName: code
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
          - AttributeName: code
            KeyType: RANGE
        TableName: ${self:custom.codesTable}
        BillingMode: PAY_PER_REQUEST

disabledDeprecations:
  - CLI_OPTIONS_SCHEMA  # serverless-rack is not compliant quite yet
